# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#
matrix:
  include:

    - language: python
    python: 
      - "2.7"
    sudo: false
    cache:
      directories: 
        - "~/.platformio"

    env:
      - PLATFORMIO_CI_SRC=caregiverHardware/src/aideHardwareCaregiver.ino

    install:
      - pip install -U platformio
      - platformio update

      #External libraries
      - wget https://github.com/Seeed-Studio/OLED_Display_96X96/archive/master.zip -O /tmp/OLED_Display_96X96.zip
      - unzip /tmp/OLED_Display_96X96.zip -d /tmp
      - wget https://github.com/knolleary/pubsubclient/archive/master.zip -O /tmp/pubsubclient.zip
      - unzip /tmp/pubsubclient.zip -d /tmp

    script:
      - platformio ci --lib="." --board=d1_mini_pro -lib="/tmp/OLED_Display_96X96-master" --lib="/tmp/pubsubclient-master"

    - language: java
    jdk:
      - openjdk8
    sudo: false

    install:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    #Init X Virtual Framebuffer
    # before_script:
    #   - "export DISPLAY=:99.0"
    #   - "sh -e /etc/init.d/xvfb start"
    #   - sleep 3

    script:
      - mvn test -B
