matrix:
  include:

  #ESP8266 Project
  - language: python
    python: "2.7"
    cache:
      directories: 
        - "~/.platformio"

    env:
      - PLATFORMIO_CI_SRC=espHardware/src/espHardware.ino

    install:
      - pip install -U platformio
      - platformio update

      #External libraries
      - wget https://github.com/Seeed-Studio/OLED_Display_96X96/archive/master.zip -O /tmp/OLED_Display_96X96.zip
      - unzip /tmp/OLED_Display_96X96.zip -d /tmp
      - wget https://github.com/knolleary/pubsubclient/archive/master.zip -O /tmp/pubsubclient.zip
      - unzip /tmp/pubsubclient.zip -d /tmp
      - wget https://github.com/adafruit/Adafruit_MPR121/archive/master.zip -O /tmp/Adafruit_MPR121.zip
      - unzip /tmp/Adafruit_MPR121.zip -d /tmp

    script:
      - platformio ci --board=d1_mini_pro --lib="." --lib="/tmp/OLED_Display_96X96-master" --lib="/tmp/pubsubclient-master" --lib="/tmp/Adafruit_MPR121-master"

  #Circuit Playground Express Project
  - language: python
    python: "2.7"
    cache:
      directories: 
        - "~/.platformio"

    env:
      - PLATFORMIO_CI_SRC=circuitPlaygroundHardware/src/circuitPlaygroundHardware.ino

    install:
      - pip install -U platformio
      - platformio update

      #External libraries
      - wget https://github.com/adafruit/Adafruit_CircuitPlayground/archive/master.zip -O /tmp/Adafruit_CircuitPlayground.zip
      - unzip /tmp/Adafruit_CircuitPlayground.zip -d /tmp

    script:
      - platformio ci --board=adafruit_circuitplayground_m0 --lib="." --lib="/tmp/Adafruit_CircuitPlayground-master"

  #JAVA MQTT Test
  - language: java
    jdk: "openjdk8"

    before_install:
      cd mqttJava

    install:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    script:
      - mvn test -B

  #JAVA MQTT Broker Test
  - language: java
    jdk: "openjdk8"

    before_install:
      cd mqttJavaServer

    install:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    script:
      - mvn test -B

  #JAVA Main Hardware Link
  - language: java
    jdk: "openjdk8"

    before_install:
      - git clone https://github.com/Grasia/phatsim.git
      - cd phatsim
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - cd ../phatHardwareLink

    install:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    #Init X Virtual Framebuffer
    # before_script:
    #   - "export DISPLAY=:99.0"
    #   - "sh -e /etc/init.d/xvfb start"
    #   - sleep 3

    script:
      - mvn test -B
